-- Solana Narrative Tracker — Full Schema + RLS
CREATE TABLE IF NOT EXISTS social_signals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), source TEXT NOT NULL, handle TEXT NOT NULL, tweet_id TEXT UNIQUE NOT NULL, tweet_text TEXT NOT NULL, tweet_url TEXT, posted_at TIMESTAMPTZ, followers_count INT, engagement JSONB DEFAULT '{}', keywords_matched TEXT[] DEFAULT '{}', category TEXT, signal_strength FLOAT DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS github_signals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), repo_full_name TEXT NOT NULL, repo_url TEXT, stars INT DEFAULT 0, stars_delta INT DEFAULT 0, forks INT DEFAULT 0, open_issues INT DEFAULT 0, recent_commits INT DEFAULT 0, language TEXT, description TEXT, topics TEXT[] DEFAULT '{}', last_push_at TIMESTAMPTZ, signal_type TEXT, scanned_at TIMESTAMPTZ DEFAULT now(), created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(repo_full_name, scanned_at));
CREATE TABLE IF NOT EXISTS onchain_signals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), signal_type TEXT NOT NULL, program_id TEXT, program_name TEXT, metric_name TEXT, metric_value FLOAT, metric_delta FLOAT, network TEXT DEFAULT 'solana-mainnet', source TEXT, metadata JSONB DEFAULT '{}', scanned_at TIMESTAMPTZ DEFAULT now(), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS narratives (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), report_period TEXT NOT NULL, narrative_name TEXT NOT NULL, narrative_slug TEXT, description TEXT NOT NULL, confidence FLOAT DEFAULT 0, signal_count INT DEFAULT 0, category TEXT, supporting_signals JSONB DEFAULT '[]', build_ideas JSONB DEFAULT '[]', status TEXT DEFAULT 'detected', created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(report_period, narrative_slug));
CREATE TABLE IF NOT EXISTS scan_runs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), scan_type TEXT NOT NULL, started_at TIMESTAMPTZ DEFAULT now(), completed_at TIMESTAMPTZ, status TEXT DEFAULT 'running', signals_found INT DEFAULT 0, error_message TEXT, metadata JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS reports (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), period_start DATE NOT NULL, period_end DATE NOT NULL, title TEXT NOT NULL, summary TEXT, narratives_count INT DEFAULT 0, total_signals INT DEFAULT 0, report_data JSONB DEFAULT '{}', published_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(period_start, period_end));
CREATE INDEX IF NOT EXISTS idx_social_signals_handle ON social_signals(handle);
CREATE INDEX IF NOT EXISTS idx_social_signals_posted ON social_signals(posted_at DESC);
CREATE INDEX IF NOT EXISTS idx_github_signals_repo ON github_signals(repo_full_name);
CREATE INDEX IF NOT EXISTS idx_narratives_period ON narratives(report_period);
CREATE INDEX IF NOT EXISTS idx_reports_period ON reports(period_start, period_end);
ALTER TABLE social_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE github_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE onchain_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE narratives ENABLE ROW LEVEL SECURITY;
ALTER TABLE scan_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY service_all ON social_signals FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY service_all ON github_signals FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY service_all ON onchain_signals FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY service_all ON narratives FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY service_all ON scan_runs FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY service_all ON reports FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY public_read ON narratives FOR SELECT USING (true);
CREATE POLICY public_read ON reports FOR SELECT USING (true);
CREATE POLICY public_read ON social_signals FOR SELECT USING (true);
CREATE POLICY public_read ON github_signals FOR SELECT USING (true);
CREATE POLICY public_read ON onchain_signals FOR SELECT USING (true);
